const langRuArr = {
  title: 'Портфолио',
  home: 'Главная',
  about: 'Обо мне',
  skills: 'Навыки',
  portfolio: 'Портфолио',
  contacts: 'Контакты',
  mainTitle: 'Портфолио. Игорь Бабин - Junior Front-end разработчик',
  headerName: 'Игорь Бабин',
  headerInfo: 'Junior Front-end разработчик 25 лет, Тамбов',
  aboutText1: 'Привет, я Игорь - Junior Front-end разработчик из Тамбова. Интересуюсь front-end разработкой и всем, что связано с этим.',
  aboutText2: 'Прошел курсы в HTML Academy по HTML/CSS и JavaScript.',
  aboutText3: 'Буду рад работать над интересными проектами в дружном коллективе.',
  skillsText: 'Я знаю такие технологии, как',
  portfolioText1: 'Одностраничный сайт - Mavic 2 Pro',
  portfolioText2: 'React поисковый сервис фильмов',
  portfolioText3: 'Сервис поиска жилья - Keksobooking',
  contactsText1: 'Хотите узнать больше или просто поболтать? Пишите!',
  contactsText2: 'Жду вас на GitHub, Telegram, VK, WhatsApp',
  contactsBtn: 'Написать',
}
